services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup bide-bot-prod bide-bot-testing
    restart: always

  prod:
    image: ghcr.io/bide-official/bide-telegram-bot:stable
    container_name: bide-bot-prod
    restart: always
    env_file: .env
    volumes:
      - ./credentials:/app/credentials

  testing:
    image: ghcr.io/bide-official/bide-telegram-bot:testing
    container_name: bide-bot-testing
    restart: always
    env_file: .env.testing
    volumes:
      - ./credentials:/app/credentials
