services:
  watchtower:
    image: nickfedor/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup bot-stable bot-testing
    restart: always

  bot-stable:
    image: ghcr.io/bide-official/bide-telegram-bot:stable
    container_name: bot-stable
    restart: always
    env_file: .env
    volumes:
      - ./credentials:/app/credentials

  bot-testing:
    image: ghcr.io/bide-official/bide-telegram-bot:testing
    container_name: bot-testing
    restart: always
    env_file: .env.testing
    volumes:
      - ./credentials:/app/credentials
